name: iOS Optimized CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode 16.0.0
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.0.0'
      - name: Cache DerivedData
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-deriveddata-${{ hashFiles('**/*.xcodeproj/**', '**/*.swift') }}
          restore-keys: |
            ${{ runner.os }}-deriveddata-

      - name: Build Project
        run: |
          set -o pipefail && \
          xcodebuild build-for-testing \
            -scheme iOS-actions \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.0' \
            -enableCodeCoverage YES
      - name: Run test without buiding
        run: |
          set -o pipefail && \
          xcodebuild test-without-building \
           -scheme iOS-actions \
           -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.0' \
           -only-testing:iOS-actionsTests \
           -enableCodeCoverage YES

      
      - name: Build and upload to TestFlight
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          APP_STORE_CONNECT_API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
          APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
        run: |
          bundle exec fastlane beta

      - name: Notify Teams on Failure
        if: failure()
        run: |
          curl -H 'Content-Type: application/json' \
            -d "{\"text\": \"🚨 iOS CI build failed for commit ${{ github.sha }} by ${{ github.actor }}\"}" \
            ${{ secrets.TEAMS_WEBHOOK_URL }}

      - name: Notify Teams on Success
        if: success()
        run: |
          curl -H 'Content-Type: application/json' \
            -d "{\"text\": \"✅ iOS CI build passed successfully for commit ${{ github.sha }} by ${{ github.actor }}\"}" \
            ${{ secrets.TEAMS_WEBHOOK_URL }}


