name: iOS Starter Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode 16.2.0
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.2.0'

      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod install || true

      - name: Build and Test
        run: |
          xcodebuild test \
            -project iOS-actions.xcodeproj \
            -scheme iOS-actions \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Plus,OS:18.1' \
            ONLY_ACTIVE_ARCH=YES | xcpretty


        - name: Notify Teams on Failure
          if: failure()
          run: |
            curl -H 'Content-Type: application/json' \
              -d '{"text": "🚨 iOS CI build failed for commit ${{ github.sha }} by ${{ github.actor }}"}' \
              ${{ secrets.TEAMS_WEBHOOK_URL }}

        - name: Notify Teams on Success
        if: success()
        run: |
          curl -H 'Content-Type: application/json' \
            -d '{"text": "✅ iOS CI build and tests passed successfully for commit ${{ github.sha }} by ${{ github.actor }}"}' \
            ${{ secrets.TEAMS_WEBHOOK_URL }}



          